config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/show'
  devise_for :users
  root to: "dashboards#home"

  resources :games do
    resources :participations, only: ['create']

    member do
      get :edit_score
      patch :update_score
    end
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :participations, only: ['index', 'edit', 'update'] do
    resources :reviews, only: ['create']
  end

  resources :users, only: ['show'] do
    resources :chatrooms, only: :index
  end

  get :mygames, to: "dashboards#mygames"
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :game_type
  has_many :games, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :games_as_participant, through: :participations, source: :game
  has_many :chatrooms, through: :games_as_participant
  has_many :reviews, dependent: :destroy
  has_many :reviews_as_participant, through: :participations, source: :reviews
  has_many :messages, dependent: :destroy
  has_one_attached :photo
  # before_save :attach_photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # LINES COMMENTED BECAUSE NOT ASKED IN THE SIGNUP PAGE
  # validates :username, presence: true, uniqueness: true
  # validates :first_name, presence: true
  # validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  def attach_photo
    return if photo.attached?

    self.photo.attach(io: File.open(File.join(Rails.root, 'app/assets/images/default_avatar.jpg')), filename: 'avatar')
  end

  def mygames
    self.games_as_participant
  end

  def games_not_participating_and_to_come
    Game.not_participating_games_to_come_for(self)
  end

  def average_level
    total = participations.where.not(level: nil).sum(:level)
    total.fdiv(participations.where.not(level: nil).count).round(1)
  end

  def current_level(participations = self.participations.where.not(level: nil).joins(:game).where(games: { competitive: true }).where("games.start_at < ?", Time.now + 7_200).order("games.start_at ASC"))
    participations.reduce(2) do |sum, p|
      sum += p.level.fdiv(30)
    end.round(1)
  end

  def past_games_with_score
    Game.joins(participations: :user)
        .where.not(participations: { score: nil })
        .where(users: { id: self.id })
        .where("games.start_at <= ?", Time.now.in_time_zone)
        .order("games.start_at ASC")
  end

  def past_competitive_games_with_score
    past_games_with_score.where(competitive: true)
  end

  def victories_number
    past_games_with_score.count { |g| g.winner == self  }
  end

  def competitive_victories_number
    past_competitive_games_with_score.count { |g| g.winner == self  }
  end

  def level_history_data
    past_competitive_games_with_score.includes(:participations).map do |game|
      date = game.start_at
      previous_games = past_competitive_games_with_score.where("start_at <= ?", date)
      # level_at_the_time = previous_games.map { |g| g.participations.find_by(user_id: self.id) }.reduce(2) do |sum, p|
      level_at_the_time = current_level(participations.where(game: previous_games))
      [date, level_at_the_time]
    end.to_h
  end

  def level_history_data_2
    past_competitive_games_with_score.map do |game|
      date = game.start_at
      previous_games = games.where("start_at < ?", date)
      # level_at_the_time = previous_games.map { |g| g.participations.find_by(user_id: self.id) }.reduce(2) do |sum, p|
      level_at_the_time = participations.where(game: previous_games).sum("participations.level / 30")
      [date, level_at_the_time]
    end.to_h
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    # @victories = @user.mygames.select { |game| game.winner == @user }
    @victories = @user.victories_number
    @number_of_games = @user.past_games_with_score.count
    @personality_rating = @user.reviews_as_participant.sum(:personality_rating)
  end

  private

  def user_params
    params.require(:user).permit(:photo)
  end
end

app/views/users/show.html.erb
<div class="container mt-3 pt-0">
  <div class="d-flex d-print-inline-block justify-content-between mb-4 mx-3">
    <%= link_to user_chatrooms_path(current_user) do %>
      <i class="fa-regular fa-comments icone link"></i>
    <% end %>
    <h2>Profile</h2>
    <div>
      <i class="fa-solid fa-bars icone" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to "Home", root_path, class: "dropdown-item" %>
        <%= link_to "Messages", user_chatrooms_path(current_user), class: "dropdown-item" %>
        <%= link_to "Edit profile", "#", class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
      </div>
    </div>
  </div>
  <div class="d-flex mx-3 mb-5">
    <div class="col-6" id= "user-profile">
      <%= link_to user_path(@user) do %>
        <%= cl_image_tag @user.photo.key, class: "avatar-xlarge" %>
      <% end %>

      <% if @personality_rating > 0 %>
        <span class="badge text-bg-danger p-2 icon"><i class="fa-regular fa-face-laugh-wink"></i> Cool player</span>
      <% end %>
    </div>
    <div class="col-6 text-end mt-3">
      <h2><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h2>
    </div>
  </div>

  <div class="d-flex justify-content-evenly mb-4">
    <div class="col-4 d-grid gap-2 d-flex flex-column">
      <button type="button" class="btn btn-secondary border border-1 border-primary rounded-4">Edit profile</button>
      <div class="d-flex justify-content-center mt-3">
        <div class="d-flex flex-column align-items-center">
          <div>
            <i class="fa-solid fa-dice icone"></i>
          </div>
          <div>
            <strong><%= @number_of_games %></strong>
          </div>
        </div>
      </div>
    </div>
    <div class="col-4 d-grid gap-2">
      <button type="button" class="btn btn-primary shadow rounded rounded-4">Statistics</button>
      <div class="d-flex justify-content-center mt-3">
        <div class="d-flex flex-column align-items-center">
          <div>
            <i class="fa-solid fa-medal icone"></i>
          </div>
          <div>
            <strong><%= @victories %></strong>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div>
    <div class="card-profile d-flex justify-content-between">
      <div class="card-profile-infos">
        <h5>Tarot</h5>
        <h4>Level <%= @user.current_level %></h4>
        <p>Reliability: <%= @user.participations.count %>%</p>
      </div>
      <%= image_tag "tarot_cards.jpg" %>
    </div>
  </div>

  <div>
    <% if (@user.participations.count != 0)  %>
      <%= line_chart @user.level_history_data, min: (@user.level_history_data.values.min - 0.5), max: (@user.level_history_data.values.max + 0.5), colors: ["#ff7a59", "#001333"]%>
    <% end %>
  </div>
</div>