config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/show'
  devise_for :users
  root to: "dashboards#home"

  resources :games do
    resources :participations, only: ['create']

    member do
      get :edit_score
      patch :update_score
    end
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :participations, only: ['index', 'edit', 'update'] do
    resources :reviews, only: ['create']
  end

  resources :users, only: ['show'] do
    resources :chatrooms, only: :index
  end

  get :mygames, to: "dashboards#mygames"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_game_card.erb
<div class="game-card">
  <div class="game-time">
    <p><i class="fa-regular fa-calendar"></i> Wednesday 28 june</p>
    <p><i class="fa-regular fa-clock"></i> 10:00</p>
  </div>
  <div class="players">
      <div class="player">
        <img class="avatar-card" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" class="avatar"/>
        <p>Name</p>
      </div>
      <div class="player">
        <img class="avatar-card" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" class="avatar"/>
        <p>Name</p>
      </div>
      <div class="player">
        <img class="avatar-card" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" class="avatar"/>
        <p>Name</p>
      </div>
      <div class="player">
        <img class="avatar-card" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" class="avatar"/>
        <p>Name</p>
      </div>
  </div>
  <div class="game-type">
    <p><i class="fa-regular fa-card-spade"></i><strong> Tarot</strong></p>
    <p><i class="fa-regular fa-card-spade"></i><strong> Competitive</strong></p>
  </div>
</div>

<%#= render "game_card", game: @game %>

app/views/shared/_game_card_join.html.erb
<%= link_to game_path(game) do %>
  <% if game.start_at >= DateTime.now %>
    <div class="game-card">
      <div class="game-time">
        <p class="text-decoration-none"><strong><%= truncate(game.city, length: 15) %></strong></p>
        <p><i class="fa-regular fa-calendar"></i><%= game.start_at.strftime("%a %d %b") %> <%= game.start_at.strftime("%H:%M") %></p>
      </div>
      <div class="players">
        <% game.participations.map do |participation|%>
          <div class="player">
            <%= cl_image_tag participation.user.photo.key, class: "avatar-card" %>
            <p><%= participation.user.first_name.capitalize.truncate(6) %></p>
          </div>
        <% end %>
        <% unless game.participations.count == game.number_of_players %>
          <% (game.number_of_players - game.participations.count).times do %>
            <div class="player">
              <div class="btn btn-add"><i class="fa-solid fa-plus"></i></div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="game-type">
        <p><i class="fa-solid fa-diamond"></i><strong><%= game.game_type.name %></strong></p>
        <p>
          <% if game.competitive == true %>
            <strong><%= "Competitive" %> <i class="fa-solid fa-trophy"></i></strong>
          <% else %>
            <strong><%= "Friendly" %> <i class="fa-solid fa-handshake-angle"></i></strong>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_message.html.erb
<div id="message-<%= message.id %>" data-user-id="<%= current_user.id %>">
  <small>
    <strong><%= message.user.username %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/shared/_navbar.html.erb
<div class="bg-secondary d-flex justify-content-evenly align-items-center" id="pp-navbar">
  <% if user_signed_in? %>
    <%# HOMEPAGE BUTTON %>
    <div>
      <%= link_to root_path do %>
        <i class="fa-solid fa-house"></i>
      <% end %>
    </div>
    <%# SEARCH BUTTON %>
    <div>
      <%= link_to games_path do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    </div>
    <%# NEW GAME BUTTON %>
    <div class="d-flex align-items-center" id="new-game-btn">
      <%= link_to new_game_path do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
    </div>
    <%# CALENDAR BUTTON %>
    <div>
      <%= link_to games_path do %>
        <i class="fa-regular fa-calendar-days"></i>
      <% end %>
    </div>
    <%# PROFILE USER BUTTON %>
    <div>
      <%= link_to user_path(current_user) do %>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar" %>
      <% end %>
    </div>

  <% else %>
    <div>
      <%= link_to "Login", new_user_session_path %>
    </div>
  <% end %>
</div>

app/views/shared/_news_card.html.erb
<div class="news-cards">
  <% User.all.shuffle.first(2).each do |user| %>
    <div class="news-card-infos <%= "d-none" if ((user.participations.last.game.start_at < Date.today) && (user.participations.last.game.winner) && (user != current_user)) == false %>">
      <p><%= user.first_name.capitalize %> recently won a game of <%= user.participations.last.game.game_type.name %>!</p>
      <img src="https://media.istockphoto.com/id/1342048331/fr/vectoriel/main-tenant-un-troph%C3%A9e-acclam%C3%A9-par-dautres.jpg?s=612x612&w=0&k=20&c=q0W7eUrIsjQHnI6QcINUG_PjkWs7JeOOkQfKdAyhV7I=" />
    </div>
  <% end %>
  <% User.all.shuffle.first(2).each do |user| %>
    <div class="news-card-infos <%= "d-none" if ((user.participations.last.game.start_at < Date.today) && (user != current_user)) == false %>">
      <p><%= user.first_name.capitalize %> made a score of <%= user.participations.last.score %> points!</p>
      <img src="https://play-lh.googleusercontent.com/n410wbqCMcGZ3ZWFytQR4JN2RyRii3SliKO978j8_AlE7716Ax6n7VjcNvqdHGS9SYs6" />
    </div>
  <% end %>
</div>

app/views/shared/_passed_card_game.erb
<%= link_to game_path(game) do %>
  <% if game.start_at - 7_200 < DateTime.now %>
    <div class="game-card">
      <div class="game-time">
        <p class="text-decoration-none"><%= truncate(game.city, length: 15) %></p>
        <p><i class="fa-regular fa-calendar"></i><%= game.start_at.strftime("%a %d %b %H:%M") %></p>
      </div>
      <div class="players">
        <% g = game.participations.order(:score).reverse %>
        <% if game.participations.where(score: 0).length == game.number_of_players%>
          <% g.map do |participation|%>
            <div class="player">
              <%= cl_image_tag participation.user.photo.key, class: "avatar-card" %>
              <p><%= participation.user.first_name.capitalize %></p>
            </div>
          <% end %>
        <% else %>
          <% g.map do |participation|%>
            <div class="player">
              <% if g.first == participation %>
                <%= cl_image_tag participation.user.photo.key, class: "avatar-card-winner" %>
                <p><%= participation.user.first_name.capitalize %></p>
              <% elsif g.second == participation %>
                <%= cl_image_tag participation.user.photo.key, class: "avatar-card-second" %>
                <p><%= participation.user.first_name.capitalize %></p>
              <% elsif g.third == participation %>
                <%= cl_image_tag participation.user.photo.key, class: "avatar-card-third" %>
                <p><%= participation.user.first_name.capitalize %></p>
              <% else %>
                <%= cl_image_tag participation.user.photo.key, class: "avatar-card" %>
                <p><%= participation.user.first_name.capitalize %></p>
              <% end %>
            </div>
          <% end %>
        <% end %>
        <% unless game.participations.count == game.number_of_players %>
          <% (game.number_of_players - game.participations.count).times do %>
            <div class="player">
              <div class="btn btn-add"><i class="fa-solid fa-plus"></i></div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="game-type">
        <p><i class="fa-solid fa-diamond"></i><%= game.game_type.name %>
          <% if game.participations.where(score: 0).length == game.number_of_players%>
              <span class="badge text-bg-primary text-light">Add scores</span>
          <% end %>
        </p>
        <p><i class="fa-solid fa-ranking-star"></i>
          <% if game.competitive == true %>
            <%= "Competitive" %>
          <% else %>
            <%= "Friendly" %>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_pp_navbar.html.erb
<div class="bg-secondary d-flex justify-content-evenly align-items-center" id="pp-navbar">
  <% if user_signed_in? %>
    <%# HOMEPAGE BUTTON %>
    <div>
      <%= link_to root_path do %>
        <i class="fa-solid fa-house"></i>
      <% end %>
    </div>
    <%# SEARCH BUTTON %>
    <div>
      <%= link_to games_path do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    </div>
    <%# NEW GAME BUTTON %>
    <div class="d-flex align-items-center" id="new-game-btn">
      <%= link_to new_game_path do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
    </div>
    <%# CALENDAR BUTTON %>
    <div>
      <%= link_to mygames_path do %>
        <i class="fa-regular fa-calendar-days"></i>
      <% end %>
    </div>
    <%# PROFILE USER BUTTON %>
    <div>
      <%= link_to user_path(current_user) do %>
        <%= cl_image_tag current_user.photo.key, class: "avatar" %>
      <% end %>
    </div>

  <% else %>
    <div>
      <%= link_to "Login", new_user_session_path %>
    </div>
  <% end %>
</div>

app/views/shared/_search_filters.html.erb
      <%# GAME TYPES RADIO BUTTONS %>
      <fieldset class="mb-3 radio_buttons required game_game_type">
        <legend class="col-form-label pt-0">Game type<abbr title="required">*</abbr></legend>
        <input type="hidden" name="game_type_id" value="" autocomplete="off">
        <div class="label-inline">
          <input class="form-check-input radio_buttons required button-hide" type="radio" value="1" name="game_type_id" id="game_type_id_1">
          <label class="form-check-label collection_radio_buttons" for="game_type_id_1">Tarot</label>
        </div>
        <div class="label-inline">
          <input class="form-check-input radio_buttons required button-hide" type="radio" value="2" name="game_type_id" id="game_type_id_2">
          <label class="form-check-label collection_radio_buttons" for="game_type_id_2">Rami</label>
        </div>
      </fieldset>

      <%# DURATION BAR %>
      <div data-controller="range" class="mx-5">
        <label for="duration[range]"><strong>Duration</strong> <span data-range-target="rangeElement">2h15</span></label>
          <div id="duration-range">
            <div class="mb-3 range required game_duration">
              <input class="form-range numeric range required" min="30" max="240" step="15" data-action="input->range#range" data-range-target="input" type="range" name="duration" id="duration">
            </div>
          </div>
      </div>

      <%# NUMBER OF PLAYERS RADIO BUTTONS %>
      <fieldset class="mb-3 radio_buttons required game_number_of_players">
        <legend class="col-form-label pt-0">Number of players <abbr title="required">*</abbr></legend>
        <input type="hidden" name="number_of_players" value="" autocomplete="off">
        <% (3..5).to_a.each do |index| %>
          <div class="label-inline">
            <input class="form-check-input radio_buttons required button-hide" type="radio" value="<%= index %>" name="number_of_players" id="game_number_of_players_<%= index %>">
            <label class="form-check-label collection_radio_buttons" for="game_number_of_players_<%= index %>"><%= index %></label>
          </div>
        <% end %>
      </fieldset>

      <%# COMPETITIVE TOGLE BUTTON %>
      <fieldset class="mb-3 boolean optional game_competitive">
        <div class="form-check">
          <input name="competitive" type="hidden" value="0" autocomplete="off">
          <input class="form-check-input boolean optional toggle" type="checkbox" value="1" name="competitive" id="competitive">
          <label class="form-check-label boolean optional" for="competitive">Competitive</label>
        </div>
      </fieldset>