config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/show'
  devise_for :users
  root to: "dashboards#home"

  resources :games do
    resources :participations, only: ['create']

    member do
      get :edit_score
      patch :update_score
    end
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :participations, only: ['index', 'edit', 'update'] do
    resources :reviews, only: ['create']
  end

  resources :users, only: ['show'] do
    resources :chatrooms, only: :index
  end

  get :mygames, to: "dashboards#mygames"
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :game_type
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations
  has_one :chatroom, dependent: :destroy

  validates :location, presence: true
  validates :start_at, presence: true
  validates :duration, presence: true, numericality: { only_integer: true }, comparison: { greater_than: 0 }
  validates :number_of_players, presence: true, numericality: { only_integer: true }, comparison: { greater_than: 0, less_than_or_equal_to: 5 }
  # validates :competitive, presence: true

  accepts_nested_attributes_for :participations

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  after_create :create_participation_for_owner
  after_create :create_chatroom

  scope :not_participating_games_to_come_for, ->(user) {
    where.not(id: user.games_as_participant.pluck(:id))
    .where("start_at > ?", Time.now + 7_200)
    .order(:start_at)
  }

  def winner
    self.participations.where.not(score: nil).max_by(&:score).user
  end

  def create_participation_for_owner
    Participation.create(game: self, user: self.user, status: 1, score: 0)
  end

  def create_chatroom
    Chatroom.create(game_id: id)
  end

  def city
    location.split(',').last.strip.split(' ').last
  end
end

app/models/game_type.rb
class GameType < ApplicationRecord
  has_many :users
  has_many :games

  validates :name, presence: true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit_score, :update_score]

  def index
    @games = current_user.games_not_participating_and_to_come
    @games = @games.near(params[:query], 5) if params[:query].present?
    @games = @games.where(game_type_id: params[:game_type_id]) if params[:game_type_id].present?
    @games = @games.where(number_of_players: params[:number_of_players]) if params[:number_of_players].present?
    @games = @games.where(competitive: params[:competitive]) if params[:competitive].present?
    
    @games = @games.select { |game| game.number_of_players > game.participations.count }


    respond_to do |format|
      format.html
      format.text { render partial: "games/list", locals: { games: @games }, formats: [:html] }
    end
  end

  def show
    @message = Message.new
    @participation = Participation.new
    @chatroom = @game.chatroom
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    @game.status = 0
    if @game.save
      redirect_to game_path(@game)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def edit_score
  end

  def update_score
    if @game.update(game_score_params)
      redirect_to game_path(@game)
    else
      render :edit_score, status: :unprocessable_entity
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(
      :location,
      :start_at,
      :duration,
      :number_of_players,
      :competitive,
      :description,
      :game_type_id,
      :status
    )
  end

  def game_score_params
    params.require(:game).permit(participations_attributes: [:id, :score])
  end
end

app/views/games/_game_form.html.erb
<div class="container">
  <div class="mt-5">
    <%= simple_form_for game do |g| %>
      <%= g.association :game_type, as: :radio_buttons, collection: GameType.all, label_method: :name, legend_tag: false, input_html: { class: 'button-hide' }, item_wrapper_class: 'label-inline' %>
      <%= g.input :start_at,
                  as: :string,
                  label: false,
                  input_html: { data: { controller: 'datepicker' } } %>
      <div data-controller='range'>
        <label for='duration[range]'><strong>Duration</strong> <span data-range-target='rangeElement'></span></label>
        <div class="d-flex">
          <div id="duration-range">
            <%= g.input :duration, label: false, as: :range, input_html: { min:'30', max:'240', step: '15', data: { action: 'input->range#range', range_target: 'input'}} %>
          </div>
        </div>
      </div>
      <%= g.input :location,
        label: false,
        input_html: {
          data: {address_autocomplete_target: "address"},
          class: "d-none"
        },
        wrapper_html: {
          data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}
        } %>
      <div class="">
        <%= g.input :number_of_players, as: :radio_buttons, collection: 3..5, input_html: { class: 'button-hide' }, item_wrapper_class: 'label-inline' %>
        <div id="compet-select">
          <%= g.input :competitive, input_html: { class: 'toggle' } %>
        </div>
      </div>
      <%= g.input :description, label: false, placeholder: 'Description...' %>
      <div class="d-flex justify-content-center mt-4">
        <%= g.submit 'Launch game 🚀', class: 'launch-game-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/_list.html.erb
<% if games.empty? %>
  <div class="info-panels">
      <p><i class="fa-regular fa-face-grin-beam-sweat"></i>Sorry, no games found...</p>
  </div>
<% else %>
  <% if (params[:query]).blank? == true %>
  <% else %>
  <div class="info-panels">
      <p><i class="fa-regular fa-face-laugh-wink"></i><%= games.size %> <%= games.size == 1 ? "game" : "game".pluralize %> found</p>
  </div>
  <% end %>
  <% games.each do |game| %>
    <%= render "shared/game_card_join", game: game %>
  <% end %>
<% end %>

app/views/games/edit_score.html.erb
<div class="container">
  <h1>Edit scores</h1>

    <%= form_with model: @game, url: update_score_game_path(@game) do |f|%>
    <%= f.fields_for :participations do |pf| %>
      <div class="d-flex flex-column inline-block my-4">
        <div class="d-flex justify-content-between">
          <div class="d-flex flex-column align-items-center">
            <%= cl_image_tag pf.object.user.photo.key, class: "avatar" %>
            <%= pf.object.user.first_name.capitalize %>
          </div>
          <%= pf.text_area :score %>
        </div>
      </div>
    <% end %>
    <div class="d-flex justify-content-center">
      <%= f.submit class:"launch-chat-button" %>
    </div>
  <% end %>
</div>

app/views/games/index.html.erb
<div class="show-banner">
  <h2>Find a game</h2>
</div>

<div data-controller="search-games" data-search-games-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>" class="search_index_games">
  <div class="search_bar" data-controller="display-filters" >
    <%= form_with url: games_path, method: :get, html: {data: { search_games_target: "form" }} do |f| %>
      <div class="d-flex">
        <div class="location-wrapper" data-search-games-target="locationWrapper">
          <%= f.text_field :query,
                            class: "form-control d-none",
                            placeholder: "Address",
                            value: params[:query],
                            data: {
                              search_games_target: "input"
                            } %>
        </div>
        <button class="button-search-filters" data-action="click->display-filters#displayForm">
          <i class="fa-solid fa-sliders"></i>
        </button>
      </div>
      <div class="d-none" data-display-filters-target="form" >
        <%= f.select :game_type_id, options_for_select([ ["Tarot", "1"], ["Rami", "2"] ], params[:game_type_id]), prompt: "Any game" %>
        <%= f.select :number_of_players, options_for_select([ "3", "4", "5" ], params[:number_of_players]), prompt: "Players" %>
        <%= f.select :competitive, options_for_select([["competitive", true], ["friendly", false]], params[:competitive]), prompt: "Style" %>

      <%# RENDER HERE THE OTHER LIST _search_filters.html.erb ?%>

        <%= f.submit "Save", :type => "submit", class: "filters-button", data: {display_filters_target: "submit"}%>
      </div>
    <% end %>
  </div>
  <div data-search-games-target="list">
    <%= render "list", games: @games %>
  </div>
  <div class="panel_new_game">
    <%= link_to new_game_path do %>
      <p>Create a new game</p>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div class="show-banner">
  <h2>New game</h2>
</div>
<%= render "game_form", game: @game %>

app/views/games/show.html.erb
<div class="show-banner">
  <h2>Game details</h2>
</div>

<div class="game-infos-card">
  <div class="game-infos-header">
    <div class="game-type">
      <h4><%= @game.game_type.name %></h4>
    </div>
    <div class="game-style">
      <% if @game.competitive %>
        <p><strong>Competitive 🏆</strong></p>
      <% else %>
        <p><strong>Friendly 🤝</strong></p>
      <% end %>
    </div>
  </div>
  <div class="game-description">
    <p><%= @game.description %></p>
  </div>
  <div class="game-specifications">
    <div class="game-duration">
      <p><strong>Duration</strong>
        <% if (@game.duration.fdiv(60) - 0.5).round != 0 %>
          <%= (@game.duration.fdiv(60) - 0.5).round %>h
          <% if @game.duration % 60 != 0 %>
            <%= @game.duration % 60 %>
          <% end %>
        <% else %>
          <%= @game.duration % 60 %>min
        <% end %>
      </p>
    </div>
    <div class="game-participations">
      <p><strong>Players </strong><%= @game.participations.count %>/<%= @game.number_of_players %></p>
    </div>
  </div>
</div>

<div class="event-details">
  <div class="event-details-timestart">
    <p id="day"><%= @game.start_at.strftime("%d") %></p>
    <p id="month"><%= @game.start_at.strftime("%b") %></p>
    <p id="hour-text">hour</p>
    <p id="hour"><strong><%= @game.start_at.strftime("%H:%M") %></strong></p>
  </div>
  <div class="event-address">
    <p><strong>Address</strong></p>
    <p><%= @game.location %></p>
  </div>
</div>

<div>
  <div class="player-ranking" >
    <div class="player-ranking-grid">
      <p class="grid-labels"><strong>Players</strong></p>
      <p></p>
      <p class="grid-labels" id="show-game-score"><strong>Scores</strong></p>
      <p class="grid-labels <%= "d-none" unless DateTime.now > @game.start_at - 7_200 %>" id="show-game-score"><strong>Rating</strong></p>
      <p></p>
    </div>
    <% @game.participations.each do |participant| %>
      <div class="player-ranking-card player-ranking-grid">
        <%= link_to user_path(participant.user) do %>
          <%= image_tag participant.user.photo, class: "avatar" %>
        <% end %>
        <p class="ms-2 player-name"><%= participant.user.first_name.capitalize.truncate(9) %></p>
        <% if @game.start_at - 7_200 < DateTime.now %>
          <p id="show-game-score"><%= participant.score %></p>
          <%= render "reviews/review", participant: participant %>
        <% else %>
          <p class="pending-game"> — </p>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="chat-button-card">
    <div class="<%= "d-none" unless @game.participations.map(&:user).include?(current_user) %>">
      <%= link_to chatroom_path(@chatroom), class:"show-chat-button" do %>
        <i class="fa-solid fa-comments"></i> Chat
      <% end %>
    </div>
  </div>
  <div class="<%= "d-none" if @game.participations.map(&:user).include?(current_user) %>">
    <% unless @game.start_at - 7_200 < DateTime.now %>
      <% if (@game.participations.count < @game.number_of_players) && (@game.participations.where(user_id: current_user) != false ) %>
        <button type="button" class="btn button show-game-join" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <i class="fa-solid fa-plus"></i>
        </button>
      <% end %>
    <% end %>
  </div>
  <div class="show-game-cta">
    <div class="<%= "d-none" unless @game.user == current_user && DateTime.now > @game.start_at - 7_200 %>">
      <%= link_to 'Update scores', edit_score_game_path(@game), class:"show-scores-button" %>
    </div>
    <a href="whatsapp://send?text=<%= game_url(@game) %>" class="share-whatsapp">Share on Whatsapp</a>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"><%= @game.game_type.name %> game</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="flex">
          <i class="fa-solid fa-location-dot"></i>
          <p><%= @game.location %></p>
        </div>
        <div class="flex">
          <i class="fa-regular fa-clock my-2"></i>
          <p><%= @game.start_at.strftime("%A %d %B, %Y") %> at <strong><%= @game.start_at.strftime("%H:%M") %></strong></p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= simple_form_for([@game, @participation]) do |f| %>
          <%= f.submit 'Join', class:"btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/games/show_old.html.erb
<div class="scrollable-chatroom" data-controller="chatroom"
  data-chatroom-chatroom-id-value="<%= @chatroom.id %>">
  <div class="show-banner">
    <h2><%= @game.game_type.name %> game</h2>
  </div>
  <div class="container no-scroll">
    <div class="infos-game-show infos">
      <div class="item ">
        <i class="fa-regular fa-clock"></i>
        <p><%= @game.start_at.strftime("%B %d, %Y") %></p>
        <p> <%= @game.start_at.strftime("%H:%M") %></p>
      </div>
      <div class="item ">
        <i class="fa-solid fa-location-dot"></i>
        <p><%= @game.location %></p>
      </div>
    </div>

    <div class="infos-game-show infos">
      <div class="item ">
        <i class="fa-solid fa-medal"></i>
        <p>
          <% if @game.competitive == true %>
            <%= "Competitive" %>
          <% else %>
            <%= "Friendly" %>
          <% end %>
        </p>
      </div>
      <div class="item ">
        <i class="fa-solid fa-users"></i>
        <p> <%= @game.participations.count %>/ <%= @game.number_of_players %></p>
      </div>
    </div>

    <%# passed games show %>
    <div class="card-game-show">
      <ul class="people">
        <% @game.participations.each do |participant| %>
          <li>
            <%= link_to user_path(current_user) do %>
              <%= image_tag participant.user.photo, class: "avatar" %>
            <% end %>
            <p><%= participant.user.username.truncate(10) %></p>
            <% if @game.start_at - 7_200 < DateTime.now %>
              <p><%= participant.score %></p>
            <% end %>
          </li>
        <% end %>
      </ul>
      <% unless @game.start_at - 7_200 < DateTime.now %>
        <div class="book">
          <% if (@game.participations.count < @game.number_of_players) && (@game.participations.where(user_id: current_user) != false ) %>
            <!-- Button trigger modal -->
            <button type="button" class="btn button" data-bs-toggle="modal" data-bs-target="#exampleModal">
              Book
            </button>
          <% end %>
        </div>
      <% end %>
    </div>

    <h2>messages</h2>
    <%# chatroom %>
    <div class="chatroom" data-chatroom-target="messages">
      <div class="messages"  >
        <% @chatroom.messages.each do |message| %>
          <%= render "shared/message", message: message %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <%= simple_form_for [@game, @message],html: {data: { action: "turbo:submit-end->chatroom#resetForm keyup->chatroom#validate", chatroom_target:"form" }, class: "d-flex"} do |f|%>
      <%= f.input :content,
        label: false,
        placeholder: "Message ",
        wrapper_html: {class: "flex-grow-1"},
        input_html: {data: { chatroom_target: "input"}}
      %>
      <%= f.submit "Send", class: "btn btn-primary mb-3", data: { chatroom_target:"button"} %>
      <% end %>

  </div>

  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel"><%= @game.game_type.name %> game</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="flex">
          <i class="fa-solid fa-location-dot"></i>
          <p><%= @game.location %></p>
        </div>
        <div class="flex">
          <i class="fa-regular fa-clock my-2"></i>
          <p><%= @game.start_at.strftime("%A %d %B, %Y") %> at <strong><%= @game.start_at.strftime("%H:%M") %></strong></p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= simple_form_for([@game, @participation]) do |f| %>
          <%= f.submit 'Validate participation', class:"btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>