config/routes.rb
Rails.application.routes.draw do
  get 'chatrooms/show'
  devise_for :users
  root to: "dashboards#home"

  resources :games do
    resources :participations, only: ['create']

    member do
      get :edit_score
      patch :update_score
    end
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :participations, only: ['index', 'edit', 'update'] do
    resources :reviews, only: ['create']
  end

  resources :users, only: ['show'] do
    resources :chatrooms, only: :index
  end

  get :mygames, to: "dashboards#mygames"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    participation = Participation.find(params[:participation_id])
    review = Review.find_or_initialize_by(user_id: current_user.id, participation_id: participation.id)

    if params[:action_type] == "up"
      review.personality_rating = 1
    elsif params[:action_type] == "down"
      review.personality_rating = -1
    end

    review.save

    html = render_to_string(partial: "reviews/review", locals: {participant: participation }, layout: false, formats: :html)

    render json: { html: html }.to_json
  end

end

app/views/reviews/_review.html.erb
<div class="d-flex justify-content-between <%= "d-none" if participant.user_id == current_user.id %>" data-controller="like" data-like-path-value="<%= participation_reviews_path(participant) %>">
  <i data-action="click->like#boldUp" class="fa-solid fa-thumbs-up <%= "bold" if participant.reviews.find_by(user_id: current_user)&.personality_rating == 1 %>"></i>
  <i data-action="click->like#boldDown" class="fa-solid fa-thumbs-down <%= "bold" if participant.reviews.find_by(user_id: current_user)&.personality_rating == -1 %>"></i>
</div>